version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - "backend"
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "rabestro"
    reviewers:
      - "rabestro"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - "ci-cd"
    commit-message:
      prefix: "chore"
    assignees:
      - "rabestro"
    reviewers:
      - "rabestro"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - "ci-cd"
    commit-message:
      prefix: "chore"
    assignees:
      - "rabestro"
    reviewers:
      - "rabestro"
