# Project Information
site_name: "Jegors' Python Portfolio"
site_url: "https://rabestro.github.io/hyperskill-python-portfolio/"
site_author: "Jegors Čemisovs"
site_description: "A portfolio of Python projects and development journey."

# Repository Information
repo_name: "rabestro/hyperskill-python-portfolio"
repo_url: "https://github.com/rabestro/hyperskill-python-portfolio"
edit_uri: "edit/main/docs/"

# Theme Configuration
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github


# Plugins
plugins:
  - search
  - literate-nav

nav:
  - Home: index.md
  - Blog: blog/
