# Project Information
site_name: "Jegors' Python Portfolio"
site_url: "https://rabestro.github.io/hyperskill-python-portfolio/"
site_author: "Jegors Čemisovs"
site_description: "A portfolio of Python projects and development journey."

# Repository Information
repo_name: "rabestro/hyperskill-python-portfolio"
repo_url: "https://github.com/rabestro/hyperskill-python-portfolio"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rabestro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jegors-cemisovs/
    - icon: fontawesome/solid/globe
      link: https://jc.id.lv

# Theme Configuration
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - literate-nav
  - tags:
      tags: false
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py


# Markdown Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
