name: Quality Checks

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.21"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Create Virtual Environment
        run: uv venv

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Check formatting with Ruff
        run: uv run ruff format --check .

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Type check with MyPy
        run: uv run mypy src/

      - name: Run tests with Pytest
        run: uv run pytest

      - name: Generate Code Metrics Reports
        if: matrix.python-version == '3.12'
        run: |
          # --- Cyclomatic Complexity Report ---
          echo "### Cyclomatic Complexity Report" >> $GITHUB_STEP_SUMMARY
          uv run radon cc src/ --show-complexity --average --total-average --md >> $GITHUB_STEP_SUMMARY

          # --- Maintainability Index Report ---
          echo "" >> $GITHUB_STEP_SUMMARY # Add a newline for spacing
          echo "### Maintainability Index Report (Higher is better)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Generate a Markdown table from Radon's JSON output using jq
          uv run radon mi src/ --json \
            | jq -r '
              ["File", "MI Score", "Rank"],
              ["-", "-", "-"],
              (.[] | to_entries[] | [.key, .value.mi, .value.rank])
              | @tsv' \
            | sed 's/\t/ | /g' \
            | awk '{print "| " $0 " |"}' >> $GITHUB_STEP_SUMMARY
