name: Publish Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.21"
          python-version: "3.12"
          enable-cache: true

      - name: Install documentation dependencies
        run: uv sync --locked --extra docs

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
